### ISSUE TITLE
Hello, I have some problem in precompilation.

### ISSUE THREAD

**Issue by fsfing** [gaurav-arya/ImagingOpt.jl#19]
Clone [WavePropagation.jl](https://github.com/gaurav-arya/WavePropagation.jl), [ImplicitAdjoints.jl](https://github.com/gaurav-arya/ImplicitAdjoints.jl) and this repo and run

dev {path to WavePropagation.jl}
dev {path to ImplicitAdjoints.jl}
dev {path to this repo}
in Julia's package manager.

Q1: What do you mean by repo here?  a repository()? 

Q2:
My installation steps:

1. I cloned your ImagingOpt.jl

2. I clone WavePropagation.jl and ImplicitAdjoints.jl, which are in the same level folder as ImagingOpt.jl.

3. I developed WavePropagation.jl, ImplicitAdjoints.jl, and ImagingOpt.jl in turn

4. Then, an error message was given:

ERROR: LoadError:  Failed to precompile WavePropagation [35738e4c-42fb-4913-b8e7-4cd0bbf068f1] to  "/ home/sffu /. Julia/compiled/v1.9 / WavePropagation/jl_f6maLI".

5. I put [deps] of Project.toml in WavePropagation.j      LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
6. Met a new mistake:
![image](https://github.com/gaurav-arya/ImagingOpt.jl/assets/57214227/f043c0fb-f438-4766-96cb-ddf7f29c74ec)
7. A mistake:
ERROR: LoadError: ArgumentError: Package ImagingOpt does not have ImplicitAdjoints in its dependencies:
8. Project.toml add ImplicitAdjoints = "dc78e922-f45c-41f9-88f5-a5d7bf3a9742" in ImagingOpt.jl
9. A mistake：
![image](https://github.com/gaurav-arya/ImagingOpt.jl/assets/57214227/24a12045-4790-425d-9c6d-ea704355f809)

As for the last error, I don't know how to solve it. I hope to get your help.

**Comment by fsfing** [comment]
example code run successfully

**Comment by gaurav-arya** [comment]
Cool! Let me know if I can edit the instructions to be more helpful.

**Comment by fsfing** [comment]
Follow the question above:

be commented out  Base.cumulative_compile_time_ns_before, Base.cumulative_compile_time_ns_after

new error:
	ERROR: LoadError: ArgumentError: Package ImagingOpt does not have ThreadsX in its dependencies

import Pkg; Pkg.add("ThreadsX")
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d" in ImagingOpt.jl -- Project.toml	

ok！
![image](https://github.com/gaurav-arya/ImagingOpt.jl/assets/57214227/6e4c7bf3-d5fa-4898-b74f-8fc98a362875)
